import { defineConfig } from "vitest/config";
import { fileURLToPath } from "node:url";

export default defineConfig({
  resolve: {
    // NOTE: order matters. Vite matches aliases in order, so the specific
    // "@/lib/db" entry must be declared before the generic "@" prefix,
    // otherwise "@" wins and the real (binary-engine) client gets loaded.
    alias: [
      {
        // The disposable client is generated by `test:generate` from the
        // committed schema with Prisma's driver-adapter engine. Runtime imports
        // of Prisma enums and SQL helpers must resolve to that same generated
        // client; otherwise a fresh checkout can accidentally load the
        // ungenerated production-client placeholder during P15 validation.
        find: /^@prisma\/client$/,
        replacement: fileURLToPath(
          new URL("./tests/.generated/client/index.js", import.meta.url),
        ),
      },
      {
        // The discovery engine and the worker import `@/lib/db-client`, the
        // unguarded client, because `server-only` throws outside a React
        // Server Component graph. Same substitution as `@/lib/db`.
        find: /^@\/lib\/db-client$/,
        replacement: fileURLToPath(
          new URL("./tests/helpers/test-prisma.ts", import.meta.url),
        ),
      },
      {
        // Application data-access code imports `@/lib/db`. In tests that same
        // code must run against the disposable test database via the driver
        // adapter, so the module is swapped here rather than in the source.
        find: /^@\/lib\/db$/,
        replacement: fileURLToPath(
          new URL("./tests/helpers/test-prisma.ts", import.meta.url),
        ),
      },
      {
        // `server-only` throws on import outside a React Server Component
        // runtime. Next.js swaps it for an empty module via the "react-server"
        // export condition; the test runner does the same so server modules
        // can be imported directly. This does not weaken the app build guard.
        find: /^server-only$/,
        replacement: fileURLToPath(
          new URL("./node_modules/server-only/empty.js", import.meta.url),
        ),
      },
      {
        find: /^@\//,
        replacement: fileURLToPath(new URL("./src/", import.meta.url)),
      },
    ],
  },
  test: {
    environment: "node",
    setupFiles: ["./tests/setup.ts"],
    include: ["tests/p15/**/*.test.ts"],
    // Integration tests share one disposable Postgres database, so they must
    // not run concurrently against each other.
    fileParallelism: false,
    testTimeout: 30_000,
    hookTimeout: 60_000,
  },
});
