import { PrismaPg } from "@prisma/adapter-pg";

// Generated by `npm run test:generate` from the real prisma/schema.prisma.
import { PrismaClient } from "../.generated/client/index.js";

import { TEST_DATABASE_URL } from "./test-db";

/**
 * Prisma Client bound to the disposable test database through the pg driver
 * adapter. `vitest.config.ts` aliases `@/lib/db` to this module, so the
 * application's own data-access code runs unmodified against real SQL.
 */
export const db = new PrismaClient({
  adapter: new PrismaPg({ connectionString: TEST_DATABASE_URL }),
});

export async function disconnectTestPrisma() {
  await db.$disconnect();
}
